name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 25
      uses: actions/setup-java@v3
      with:
        java-version: '25'
        distribution: 'temurin'
        
    # PASO NUEVO: Descargamos JUnit y Hamcrest (necesario para JUnit)
    - name: Download Dependencies
      run: |
        mkdir -p lib
        wget -O lib/junit-4.13.2.jar https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
        wget -O lib/hamcrest-core-1.3.jar https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

    - name: Compile with Javac
      run: |
        mkdir -p bin
        # Agregamos -cp "lib/*" para que javac use los jars que acabamos de bajar
        javac -d bin -cp "lib/*" $(find src -name "*.java")
        
    - name: Correr Pruebas
      run: java -cp "bin:lib/*" org.junit.runner.JUnitCore FileHelperTest